### ISSUE TITLE
master branch is hardcoded in the upstream-sync.sh

### ISSUE THREAD

**Issue by bdougie** [aormsby/Fork-Sync-With-Upstream-action#1]
# What is the issue?

I am interested in using this action for my project, but the HEAD branch is not master. Per the arguments, it is assumed that you can point to the project branch, but I found that the fetch is to master and not upstream branch argument.

Is this an oversight?

# Link

https://github.com/aormsby/Fork-Sync-With-Upstream-action/blob/master/upstream-sync.sh#L27

**Comment by aormsby** [comment]
> Is this an oversight?

Oh haha, yes. My mistake. Thanks for catching that. I'll merge in your PR and update the 'v1' tag to include it. 🙂
