### ISSUE TITLE
action fails: asks for git config

### ISSUE THREAD

**Issue by wmmc88** [aormsby/Fork-Sync-With-Upstream-action#11]
Example Here: https://github.com/wmmc88/rosdistro/runs/1305372460?check_suite_focus=true

The error is 
```
Rebasing (1/1)
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az67.pfrdwpiphmie1gjrpxwhkjfenc.gx.internal.cloudapp.net>) not allowed
Error: The process '/bin/sh' failed with exit code 128
```

**Comment by aormsby** [comment]
Oh hmm... I forgot to add user credential options to this action. I guess they're required for a rebase, but it's odd that this error didn't show up for other operations before now. Should be an easy fix. I'll take care of it and get back to you here. 🙂

**Comment by aormsby** [comment]
Fixed in new release - https://github.com/aormsby/Fork-Sync-With-Upstream-action/releases/tag/v2.1
