### ISSUE TITLE
Git's name and email swapped bug

### ISSUE THREAD

**Issue by RadWolfie** [aormsby/Fork-Sync-With-Upstream-action#19]
Hi @aormsby, I found a bug in your bash script:
https://github.com/aormsby/Fork-Sync-With-Upstream-action/blob/c86999d81e8504c61a7eae1bd12ad04eae3449e5/upstream-sync.sh#L14-L20

As you can see input email is being assigned as user.name and input user is assigned to user.email. Somehow you had them swapped in the process. The change occurred 19 days ago.

**Comment by aormsby** [comment]
Huh. Yeah. Thanks, I'll take care of this later in the week when I spend time with another issue.

**Comment by aormsby** [comment]
Fixed in [v2.3](https://github.com/aormsby/Fork-Sync-With-Upstream-action/releases/tag/v2.3) 👍
