### ISSUE TITLE
fatal: refusing to merge unrelated histories

### ISSUE THREAD

**Issue by canokaue** [aormsby/Fork-Sync-With-Upstream-action#20]
I keep getting this error on the workflow of my fork, even if I use the --ff-only flag.

Any suggestions?
![Screen Shot 2021-02-08 at 11 02 56](https://user-images.githubusercontent.com/30631118/107230071-58a85000-69fd-11eb-95e4-7b64301e39bd.png)

**Comment by aormsby** [comment]
Some stuff I wrote in the readme amount this very problem. Give this a try.

[Link](https://github.com/aormsby/Fork-Sync-With-Upstream-action#when-you-want-to-merge-into-an-acive-working-branch-not-recommended)

> When You Want To Merge Into An Acive Working Branch (Not Recommended)

> If there are no conflicts between upstream and downstream branches => set git_pull_args: '--allow-unrelated-histories'.

>This will allow divergent histories to be merged, but be careful with the results. It's very likely there will be conflicts in any merge unless you know for sure there won't be, so your mileage may vary here.

More stuff below that on merge overwrites.

If it works, please close this. If not, let me know. 😉

**Comment by canokaue** [comment]
![Screen Shot 2021-02-11 at 11 07 20](https://user-images.githubusercontent.com/30631118/107647554-0ca61700-6c5a-11eb-9c74-84394c3bd8a8.png)
Hey, I still got this error. All I'm trying to do is to keep my fork updated twice a week, the only conflicting file is the workflow itself. Appreciate the help!

**Comment by canokaue** [comment]
I actually got one repo to work following you suggestion @aormsby , but other 4 failed, don't know why.

**Comment by aormsby** [comment]
> ![Screen Shot 2021-02-11 at 11 07 20](https://user-images.githubusercontent.com/30631118/107647554-0ca61700-6c5a-11eb-9c74-84394c3bd8a8.png)

I'll need more info, I think. Is 'Fetching the repository' what you named the step where you use this action? What's your workflow like? Which one time worked (and if possible, why?) I just don't have much to go on here.

**Comment by danieletorelli** [comment]
```
       --unshallow
           If the source repository is complete, convert a shallow repository
           to a complete one, removing all the limitations imposed by shallow
           repositories.

           If the source repository is shallow, fetch as much as possible so
           that the current repository has the same history as the source
           repository.
```

@canokaue This is probably the pull argument you're searching for here instead of `--allow-unrelated-histories`.

**Comment by canokaue** [comment]
Thank you so much @danieletorelli that did the trick 😃

**Comment by aormsby** [comment]
Thank you for your help, @danieletorelli. I'm making some updates to the action, and I'll be sure to add a note about this scenario.
