### ISSUE TITLE
Default template comment is duplicated

### ISSUE THREAD

**Issue by HarelM** [aormsby/Fork-Sync-With-Upstream-action#28]
When copying the default template the pull and push comment is duplicated and therefore has a copy-paste typo...
See here:
https://github.com/aormsby/Fork-Sync-With-Upstream-action/blob/ac3bad798688ddf124b7d83a8e4fced59a1a83a7/action.yaml#L47
https://github.com/aormsby/Fork-Sync-With-Upstream-action/blob/ac3bad798688ddf124b7d83a8e4fced59a1a83a7/action.yaml#L42
Also the readme is talking about `fetch_args`, are these the same as `pull_args`?
![image](https://user-images.githubusercontent.com/3269297/119226724-4917c780-bb13-11eb-8414-1c82ef3a1063.png)

Thanks for this great Github Action!

**Comment by aormsby** [comment]
Ah I see, thanks for letting me know about the typo. About the `fetch_args` these are actually used when getting the latest updates from the upstream repo (before the merge). Then the `pull_args` are used when merging the data from upstream to the local repo. I realize it's not very clear, though, and it's possible the `fetch_args` may not even be all that useful. I'm working on a 3.0 update to the action, and I will be sure to try making that more obvious. Thanks for the feedback. :)

**Comment by aormsby** [comment]
Fixed in 2.4 and 3.0
