### ISSUE TITLE
Error: Cannot read username

### ISSUE THREAD

**Issue by iamjameswalters** [aormsby/Fork-Sync-With-Upstream-action#32]
When running the action, it fails apparently trying to read the username:

```
Pushing synced data to target branch.
fatal: could not read Username for 'https://github.com': No such device or address
ERROR:  exit 128
Could not push changes to target repo.
Try running in test mode to verify your action input. If that does not help, please open an issue.
Resetting git config to previous settings.
Reset Complete
```

When put in test mode, it appears to read it just fine:

```
TEST
[Config User Name] -> user.name should equal 'GH Action - Upstream Sync'
PASSED
```

Perhaps I've misconfigured something in my [workflow](https://github.com/iamjameswalters/VSCodePopTheme/blob/master/.github/workflows/openvsx.yml)?

**Comment by aormsby** [comment]
I believe your issue is that the upstream repo is public, so you have to remove the `upstream_repo_access_token` input var. The action uses a different URL based on if that var is included or not. Give that a shot, let me know if it works for you.

**Comment by iamjameswalters** [comment]
Removed the upstream access token line, and encountered the same error.

**Comment by PaleLebouf** [comment]
I am having this exact same issue, my workflow also looks the same.

**Comment by PaleLebouf** [comment]
I figured out the issue. It can be a publicly viewable repo, however if you need to request maintainer rights to do anything to the repo, you need an upstream access token configured.

**Comment by aormsby** [comment]
You could also try setting `git_config_user` to your own username and seeing if that works. Or any username. But I'm not sure I know the underlying cause here. I just haven't gathered enough info on the problem yet.

I'll have to clone @iamjameswalters repo and try that repo/workflow out to see what I can find out. @PaleLebouf If I can do the same for you, even more test cases. If not, no worries.

**Comment by PaleLebouf** [comment]
Unfortunately I can't, since it's a project under NDA. Sorry I'm not of more help!

**Comment by aormsby** [comment]
@PaleLebouf Can you help clarify a little for me? In your case, you're saying the upstream repo is publicly viewable, but you don't have... read permissions, I guess?

**Comment by iamjameswalters** [comment]
Adding `git_config_user: iamjameswalters` didn't work either, same error. Perhaps `No such device or address` means it can't dial out to GH/doesn't have the remote configured right at that point or something?

Beats me, but thanks for looking into this @aormsby. Let me know if I can help in any way!

**Comment by aormsby** [comment]
The problem seems to be the URL for the target repo. I made a small change so the target repo URL always gets set up with the calling user and target repo token. Please test it out by setting the action like so:

`uses: aormsby/Fork-Sync-With-Upstream-action@fix/push-url`

**Comment by iamjameswalters** [comment]
Aha, that fixed it! Thanks @aormsby

**Comment by aormsby** [comment]
Great, thanks for checking. I pushed it into `v3.0`, so no need to use that test branch anymore.
