### ISSUE TITLE
Default to 'main' branch instead of 'master'

### ISSUE THREAD

**Issue by cognifloyd** [aormsby/Fork-Sync-With-Upstream-action#7]
As described in https://github.com/github/renaming, the default branch on github is moving from `master` to `main`.
We might want to default to `main` instead of `master` as well.

Since both target and upstream branch args are currently required, this is a backwards compatible change.
Once this change is made (or as part of it), the target and upstream branch names could be made optional.

**Comment by aormsby** [comment]
To avoid confusion with defaults, I just removed them. Now all required inputs need to be set explicitly in the workflow. Changed in 6f9cf9f.
