### ISSUE TITLE
Please take action updating Node.js to 22.

### ISSUE THREAD

**Issue by codenamedpkt** [aormsby/Fork-Sync-With-Upstream-action#73]
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

For best support, we request you migrate to Node.js 22 by editing `action.yml` in root dir.

Go it now!

Alice,
Mr. Poon's Studio

**Comment by bastienmoulia** [comment]
v22 will be for November 2024 ;)

**Comment by aormsby** [comment]
PR #74 updates to v22, will make release soon
